### ISSUE TITLE
Restrict API endpoints for non-admin user

### ISSUE THREAD

**Issue by dikyarga** [id-mozilla/mozspace-jkt-backend#4]
Detail about ACL (Access Control List) documentation : https://loopback.io/doc/en/lb3/Controlling-data-access.html

Here endpoints we need to restrict :

- [x] EventTypes - non-admin only can get
- [ ] ListOfAttendees  - admin only can access
- [ ] Organizations - non-admin only can do POST (for register their organzation) and GET (to retrive existing organization, in case they have been register their organization)
- [ ] Participants - only admin can access
- [ ] Profiles - only admin can access
- [ ] RoomTypes - non-admin only can GET
- [ ] User - only admin can access
- [ ] RoleMappings - only admin can access
- [ ] RoleTypes - only admin can access

* tips : go to `/explorer/` path to see all current available endpoints and test it directly

**Comment by fadlifajrin** [comment]
saya ngerjain issue ini ya

**Comment by fadlifajrin** [comment]
`RoleMappings` dan `RoleTypes` tidak bisa diset pakai generator `lb acl` ya

**Comment by dikyarga** [comment]
> `RoleMappings` dan `RoleTypes` tidak bisa diset pakai generator `lb acl` ya

Iya, Mas. Dia bawaan soalnya, bagian ini saya lanjutkan ya, Mas. Yang PR kemarin biar _merge_ dulu aja.

Terima kasih yak
